services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5050:80"

  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        user: app
        uid: 1000
        working_dir: /var/www/backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/backend
    depends_on:
      - database
