[supervisord]
nodaemon=true
loglevel=info
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:backend-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/backend/artisan horizon
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/var/log/supervisor/backend-worker.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor/backend-worker.err.log
stderr_logfile_maxbytes=0

[program:redis-scheduler]
command=php /var/www/backend/artisan redis:schedule-loop
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/redis-scheduler.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisor/redis-scheduler.err.log
stderr_logfile_maxbytes=0

[program:php-fpm]
command=php-fpm --nodaemonize
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/php-fpm.err.log
stdout_logfile=/var/log/supervisor/php-fpm.log
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
